apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: ecarx-app
spec:
  ports:
    - port: {{ port01 }}
      protocol: TCP
      targetPort: {{ port01 }}
    - port: {{ port02 }}
      protocol: TCP
      targetPort: {{ port02 }}
  selector:
    app: {{ name }}
  type: ClusterIP