apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: ecarx-app
spec:
  ports:
    - port: {{ port }}
      protocol: TCP
      targetPort: {{ port }}
  selector:
    app: {{ name }}
  type: ClusterIP