apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
    - name: tcp-80
      port: 80
      protocol: TCP
      targetPort: 80
    - name: tcp-20880
      port: 20880
      protocol: TCP
      targetPort: 20880
  selector:
    app: nginx
  type: ClusterIP